### PR TITLE
Feature/new argument to filter entities

### PR DESCRIPTION
**Pull request by PiMaDaum**
I use the CLI extensively for loading resources and fetch there password entries. At the moment I have realized this by creating very long commands with multiple greps and cuts to extract the password from the output table.
So now I have added a new option --filter for resources and groups to filter the results. For resources if have implement this by a StringArray to define various filters of multiple columns. In the groups list command is this option defined as simple string, to filter that name.

### CODE REVIEW

**Comment by speatzle** [comment]
Hi, thanks for the PR and sorry for the Delay, i have been very busy recently.

I think this is a good feature to have,  but i also believe a filter argument has to work the same for all subcommands and also be implemented for all of them.

Additionally: 
- requires Regex Knowledge
-  does not support "OR"

I am open to discus if the regex and "OR" support are dealbreakers

**Comment by speatzle** [comment]
I did some Research and found this https://github.com/google/cel-spec

At first glance it looks exactly like what i thought. It allows complex filtering including regex.

Examples:
has(account.user_id) || has(account.gaia_id)    // true if either one is set
size(account.emails) > 0                        // true if emails is non-empty
matches(account.phone_number, "[0-9-]+")        // true if number matches regexp

Here is the introduction: https://github.com/google/cel-spec/blob/master/doc/intro.md

Do you have any concerns about implementing CEL using a --filter flag?

**Comment by PiMaDaum** [comment]
Hey @speatzle,
thanks for your feedback and your research. I agree to you, that my solution is not so flexible. But in your first comment, you criticize, that users must have a knowledge of regex. Do you think it's good for the experience, when we force users to learn the CEL specifications? 
But yes, I also think, that's a powerful option to create flexible and individual filters. However, it must then be documented precisely.
I think I'll implement it and put it additionally to this PR. So far, I have only included the function in subcommands resources and groups, because the other also have a filter as argument. Do you think, the new filter option should replace the given?
And in my opinion, we should restrict the fields to this one, which do not require an explicit query for the resource. Otherwise, we have the same performance problem as the current JSON output.

**Comment by speatzle** [comment]
Hi,

> I agree to you, that my solution is not so flexible. But in your first comment, you criticize, that users must have a knowledge of regex. Do you think it's good for the experience, when we force users to learn the CEL specifications?

I agree that if possible the user should not have to learn something new to use this project. But if it is necessary to learn something we should make it as easy as possible. In this regard, CEL is much "simpler/intuitive" to learn than regex by borrowing/sharing a syntax very similar to other projects such as bash, js, c and go which the user might already be familiar with. Regex, on the other hand, is unlike anything I know, and worst of all there are many variations of it like bash, grep, perl or php regex (although most languages like go implement perl style regex). In CEL one can also use regex very simply so those that don't want to learn CEL and already know regex could simply wrap their regex in a very basic CEL query provided by the Documentation. Example: `matches(account.phone_number, "[0-9-]+") 
`
> However, it must then be documented precisely.

I also agree that Documenting this feature with a bunch of examples and a CEL guide is essential.

>  So far, I have only included the function in subcommands resources and groups

For a first prototype it should be fine to only implement the CEL --filter flag for resources to Test and see how well that works. We can add the other Subcommands later.

> Do you think, the new filter option should replace the given?

All Filters that currently exist are API parameters where the Passbolt Server does all the filtering. I would like to keep these as they are way more performant than filtering with CEL clientside. The Documentation should be adjusted to make this clear. Additionally removing them would break compatibility with a lot of scripts made with earlier go-passbolt-cli versions.

> And in my opinion, we should restrict the fields to this one, which do not require an explicit query for the resource. Otherwise, we have the same performance problem as the current JSON output.

I think it might be possible to only load the fields if they are used in CEL or required via the Column filter. Additionally, I have a plan to fetch the Secrets alongside the Resources in a single Request instead of a Separate Request for each Secret by using the `ContainSecret` bool from the `GetResourcesOptions`  with go-passbolt's `client.GetResources` function instead of the simpler `helper.GetResource` function which is currently in use. This should help with performance.

**Comment by PiMaDaum** [comment]
I've closed this PR, because I started a new one with #26 to implement your choice with CEL.

**Pull request closed without merging**
