### PR TITLE
Get version info via ldflag during build time.

### PR DESCRIPTION
**Pull request by kskarthik**
This PR is related to our discussions in #41 

@speatzle please review

### CODE REVIEW

**Comment by kskarthik** [comment]
This commit should add the version info to the release binary

**Comment by speatzle** [comment]
Hi, thanks for the PR!

I don't think this change is necessary since the version info package should also get that flag in https://github.com/earthboundkid/versioninfo/blob/186e0577a42cee3b004e2a4b14f4155cb391fce0/legacy.go#L12

Since the package also works (git commit hash) if not built with goreleaser I'd like to keep it.

Ill run a few tests now to see what the actual issue is.

**Comment by kskarthik** [comment]
Ok, I feel that there is  no need of importing `versioninfo` as goreleaser already provides the equivalent variables

**Comment by speatzle** [comment]
One less dependency is indeed better.

But i also have instructions in the README.md to install via "go install github.com/passbolt/go-passbolt-cli@latest" where the version flag would be broken with this approach.

Thats why i wrote #48 which uses the goreleaser version if available and otherwise falls back to buildinfo (for go install and go build versions) without using the `versioninfo` package.

I Think that should make everyone happy.

**Comment by speatzle** [comment]
Fix from #48 has been released, Thank you for your help.

**Comment by kskarthik** [comment]
Feels like a good approach!

**Pull request closed without merging**
