### PR TITLE
feature/CEL filter implementation

### PR DESCRIPTION
**Pull request by PiMaDaum**
In addition to PR #23 I have implemented a filter function for resources with the [cel-go ](https://github.com/google/cel-go)library. It can be used to built dynamic filter expressions over all available columns.
**Example:**
`--filter '(Name == "SomeName" || matches(Name, "RegExpr")) && URI.startsWith("https://auth.")'`
For the references to Password and Description, I have use function references. This guarantees, that the overhead with separated queries to the server will execute only when needed. I have also tested that if the reference is used multiple times, the execution only happens once.
When you think this is fine, I can implement this solution for other commands too.

### CODE REVIEW

**Review by speatzle — CHANGES_REQUESTED** [review]
Hi, this looks very good. I just requested a few Changes to move filter related things to a seperate filter.go file and I was wondering why the `parseTimestamp` function gets Overloaded.

**Comment by PiMaDaum** [comment]
Hi @speatzle 
I outsourced the code of filtering in a separate file. And you're right. I don't know what my mistakes were, but in my first tests, the generation of a timestamp didn't work. So I implemented this overloading function. After reading the CEL specs and trying again, the built-in function _timestamp(string)_ worked fine. I've written a second example in the argument description for this.

**Review by speatzle — COMMENTED** [review]
Hi, this looks good.

We can now move on to Adding the CEL filter to Folder, Group & User List Commands.

So that we don't have to duplicate the Filter Flag definition (resource/list.go 31-35)  we can move it to the cmd/list.go file and it should then be Usable for all List Commands.

**Comment by PiMaDaum** [comment]
Hi @speatzle 
I've implemented the filter tag in the other sub-commands too. Please check and review the changes. I think now we have a usable functionality.

**Review by speatzle — APPROVED** [review]
Hi, Sorry for the delay. All Changes look good and can be Merged.

I will look at writing the Necessary Documentation Soon so that this an be released.

**Pull request merged**
