### PR TITLE
Json Output Support

### LINKED ISSUE #4: JSON format
Hi !

thanks for this awesome tool ! Do you plan to propose json format as output ? It will be easier to parse.

Thanks 😽

### PR DESCRIPTION
**Pull request by speatzle**
Supersedes #7 and fixes #4

### CODE REVIEW

**Comment by Cisien** [comment]
Decrypting values should probably be opt-in when exporting json. I get a timeout when executing a list resource command on an underpowered VM with 512mb ram and 1 core. Additionally, I don't always need the secret values when querying results. 

I need to extend the timeout to get this command to complete. 

```
passbolt list resource -j
Error: Get Resource Getting Resource Secret: Doing Request: Request Context: context deadline exceeded
```

**Comment by speatzle** [comment]
@Cisien 
> Decrypting values should probably be opt-in when exporting json.

Hmm, i am Rather split if i want to have it opt in or opt out. Since in most cases you would want to have the password. 

> I get a timeout when executing a list resource command on an underpowered VM with 512mb ram and 1 core.

Well currently it fetches the secret for each resource separately which is a waste of time. I think i could get it to fetch those all in the initial resource request but i would have to update go-passbolt.

**Comment by Cisien** [comment]
If you decide to keep it opt out, it would be useful to be able to opt out :) (perhaps by leveraging the column filters?)

**Comment by speatzle** [comment]
> If you decide to keep it opt out, it would be useful to be able to opt out :) (perhaps by leveraging the column filters?)

I made a issue to track this #24 before i forget. I am currently Pretty busy so ill implement this some time SoonTM.

**Pull request merged**
